### ISSUE TITLE
Game crashes upon placing lectern in minecraft

### ISSUE THREAD

**Issue by TranquilStar** [JamiesWhiteShirt/reach-entity-attributes#15] opened 2022-03-24 03:25 UTC
was sent by a mod author to give information on a bug that has been happening when placing a lectern.

It happens in both 1.18.2 and 1.18.1 when trying to place the lectern

[crash-2022-03-23_23.05.26-client.txt](https://github.com/JamiesWhiteShirt/reach-entity-attributes/files/8338165/crash-2022-03-23_23.05.26-client.txt)

the following above is the crash report

**Comment by TranquilStar** [comment] 2022-03-24 03:27
the mod author was MoriyaShiine

**Comment by ChloeDawn** [comment] 2022-03-24 15:33
I am unable to reproduce this with only reach-entity-attributes present. Tested on 1.18.1 and 1.18.2 in both singleplayer and multiplayer.

**Comment by ChloeDawn** [comment] 2022-03-24 15:34
Please reproduce this with the `-Dmixin.dumpTargetOnFailure=true` flag and check the dumped class for redirector conflicts

**Comment by TheRanker** [comment] 2022-03-26 16:38
this crash is happening 100% of the time using any datapack that has a strcuture with a lecturn in it and going to that chunk with a lecturn in it..  i have about 20 crash logs for this mod crashing due to a lectern block entity.    Every crash goes back to this reach entity attributes json mixin...
[crash-2022-03-23_21.53.12-server.txt](https://github.com/JamiesWhiteShirt/reach-entity-attributes/files/8355885/crash-2022-03-23_21.53.12-server.txt)
[crash-2022-03-24_13.27.40-server.txt](https://github.com/JamiesWhiteS
[crash-2022-03-26_13.56.40-server.txt](https://github.com/JamiesWhiteShirt/reach-entity-attributes/files/8355888/crash-2022-03-26_13.56.40-server.txt)
hirt/reach-entity-attributes/files/8355886/crash-2022-03-24_13.27.40-server.txt)
[crash-2022-03-24_18.41.53-server.txt](https://github.com/JamiesWhiteShirt/reach-entity-attributes/files/8355887/crash-2022-03-24_18.41.53-server.txt)

**Comment by TranquilStar** [comment] 2022-03-26 16:54
Sorry I was unable to message/reply sooner, i was busy

**Comment by TranquilStar** [comment] 2022-03-26 16:54
It seems tho someone has done it already

**Comment by TranquilStar** [comment] 2022-03-26 16:55
If not then I can do it today

**Comment by ChloeDawn** [comment] 2022-03-26 17:29
> this crash is happening 100% of the time using any datapack that has a strcuture with a lecturn in it and going to that chunk with a lecturn in it

This is the context that was missing from the original ticket. The original report stated it was on *placement*. I will look into this later today, although I still suspect it is a mod conflict.

**Comment by ChloeDawn** [comment] 2022-03-26 18:40
So, looking at the stacktrace, it's the same general issue that would trigger when the class is loaded. I cannot reproduce this at all. I need a class dump for your modpack using the `-Dmixin.dumpTargetOnFailure=true` flag. The dumped class after the crash can be found in `<instance>/.mixin.out/class/net/minecraft/class_3722$1.class`.

**Comment by TranquilStar** [comment] 2022-03-26 19:15
It only happened with bewitchment is the thing, so how do I go about doing the flag

**Comment by TheRanker** [comment] 2022-03-26 19:18
tested this with my modapck..
https://www.curseforge.com/minecraft/modpacks/rankersmp-exploratory-revelations
Replicated the crash without any issue.. heres the class file found after crash.
[class_3722$1.target.zip](https://github.com/JamiesWhiteShirt/reach-entity-attributes/files/8356202/class_3722.1.target.zip)

**Comment by TranquilStar** [comment] 2022-03-26 19:18
> > this crash is happening 100% of the time using any datapack that has a strcuture with a lecturn in it and going to that chunk with a lecturn in it
> 
> This is the context that was missing from the original ticket. The original report stated it was on _placement_. I will look into this later today, although I still suspect it is a mod conflict.

I think I said it in the first ticket when I was doing it for bewitchment I guess I forgot to add this detail my bad.

Just tell me how to do the flag and I'll go ahead a see in a few

**Comment by ChloeDawn** [comment] 2022-03-26 20:02
Okay, this is a conflict with Pekhui's redirector, please report it to them, as they need to update their compatibility.

**Comment by TranquilStar** [comment] 2022-03-26 20:04
Should I or ranker

**Comment by ChloeDawn** [comment] 2022-03-26 20:06
It's fine, I'll notify them

**Comment by TranquilStar** [comment] 2022-03-27 07:54
so I found out that downgrading it makes lecterns useable Pehkui

**Comment by YaBoi2Fish** [comment] 2022-03-27 10:55
To which version you downgraded to?


> so I found out that downgrading it makes lecterns useable Pehkui

**Comment by TranquilStar** [comment] 2022-03-27 11:31
> To which version you downgraded to?
> 
> > so I found out that downgrading it makes lecterns useable Pehkui

Pehkui-3.1.0+1.14.4-1.18.1.jar

**Comment by TranquilStar** [comment] 2022-03-27 11:31
idk about 1.18.2 for 1.18.1 this was the fix for me, sucks that I didnt try this sooner because my world got corrupted the first time I found this issue

**Comment by Virtuoel** [comment] 2022-03-29 09:41
Fixed as of Pehkui 3.2.1.

**Comment by ChloeDawn** [comment] 2022-03-29 09:42
Fixed in Pehkui 3.2.1

**Closed as completed** 2022-03-29 09:42 UTC
Labels: bug, other mod
